DrawCommunityMatrix <- function(A, x, y, cex, lod) {
  
  # Add a graph representing a community matrix to an existing plot
  #
  # Arguments:
  # A           Community matrix (e.g. generated by GetCommunityMatrix)
  # x,y         Coordinates of center of graph
  # cex         Relative size of graph
  # lod         Level of detail (can make simpler versions when drawing many small)
  #
  # Remarks:
  # The function assumes the overall plot extends from -1 to 1 in horizontal and vertical.
  

radius <- cex
point.cex <- cex

S <- nrow(A)

theta <- seq(0, 2*pi, length.out = S+1)[-1]
x <- x + radius*cos(theta)
y <- y + radius*sin(theta)

for (i in 2:S){
  for (j in 1:(i-1)){
    if (A[i,j] != 0) {
      
      a <- A[i,j]
      b <- A[j,i]
      
      segments(x[i], y[i], x[j], y[j], col = rgb(0,0,0,10/S))
      
    }
  }
}

}
