DrawCommunityMatrix <- function(A) {
  
  # Add a graph representing a community matrix to an existing plot
  #
  # Arguments:
  # A           Community matrix (e.g. generated by GetCommunityMatrix)
  # x,y         Coordinates of center of graph
  # cex         Relative size of graph
  
}


